//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoptextno1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class truyen
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string tinhtrang { get; set; }
        public string mota { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> idLoai { get; set; }
        public string img { get; set; }
    
        public virtual theloai theloai { get; set; }
    }
}
